markets:
  - name:   BTCUSDT
    base:   BTC
    quote:  USDT
    base_precision: 8
    quote_precision: 2
  - name:   ETHUSDT
    base:   ETH
    quote:  USDT
    base_precision: 5
    quote_precision: 2

exchanges:
  - name: binance
    url:  "https://www.binance.com"
    rest: "https://api.binance.com"
    ws:   "wss://api.binance.com"
    rate: 1.0

  - name: bitfaker
    url:  "https://www.bitfaker.com"
    rest: "https://api.bitfaker.com"
    ws:   "wss://api.bitfaker.com"
    rate: 1.0

  - name: bitfinex
    url:  "https://www.bitfinex.com"
    rest: "https://api.bitfinex.com/v1"
    ws:   "wss://api.bitfinex.com/ws"
    rate: 1.0

  - name: hitbtc
    url:  "https://www.hitbtc.com"
    rest: "https://api.hitbtc.com/api/2"
    ws:   "wss://api.hitbtc.com/api/2/ws"
    rate: 1.0

  - name: huobi
    url:  "https://www.hbg.com"
    rest: "https://api.huobi.pro"
    ws:   "wss://api.huobi.pro/ws"
    rate: 1.0

  - name: kraken
    url:  "https://www.kraken.com"
    rest: "https://api.kraken.com"
    ws:   "wss://ws.kraken.com"
    rate: 1.0

  - name: luno
    url:  "https://www.luno.com"
    rest: "https://api.mybitx.com/api/1"
    ws:   "wss://ws.luno.com/api/1/stream"
    rate: 1.0

  - name: okex
    url:  "https://www.okex.com"
    rest: "https://www.okex.com/api"
    ws:   "wss://real.okex.com:10442/ws/v3"
    rate: 1.0

  - name: rubykube
    url:  "https://www.devkube.com"
    rest: "https://www.devkube.com/api/v2/peatio"
    ws:   "wss://www.devkube.com"
    rate: 1.0
